### ISSUE TITLE
Can't add alongpath component in Inspector.

### ISSUE THREAD

**Issue by pfreema1** [aframevr/aframe-inspector#464]
When I click the "Add component" dropdown, and select "alongpath," nothing comes up.

Browser is Google Chrome Version 57.0.2987.98

**Comment by fernandojsg** [comment]
Yep, I can reproduce it. It seems like a incompatibility between alongpath and latest aframe:
```
aframe-alongpath-component.min.js:1 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty.
    at NewComponent.update (https://unpkg.com/aframe-alongpath-component@1.0.4/dist/aframe-alongpath-component.min.js:1:624)
    at NewComponent.updateProperties (https://aframe.io/aframe-inspector/example/js/aframe-master.js:63051:12)
    at NewComponent.module.exports.Component (https://aframe.io/aframe-inspector/example/js/aframe-master.js:62876:8)
    at new NewComponent (https://aframe.io/aframe-inspector/example/js/aframe-master.js:63169:15)
    at HTMLElement.value (https://aframe.io/aframe-inspector/example/js/aframe-master.js:61757:47)
    at HTMLElement.value (https://aframe.io/aframe-inspector/example/js/aframe-master.js:61908:12)
    at componentUpdate (https://aframe.io/aframe-inspector/example/js/aframe-master.js:62100:14)
    at HTMLElement.value (https://aframe.io/aframe-inspector/example/js/aframe-master.js:62069:11)
    at addComponent (https://aframe.io/aframe-inspector/dist/aframe-inspector.js:11764:17)
```

**Comment by fernandojsg** [comment]
I'll close it as it's related to the component itself, so we could keep track on the registry itself
