### ISSUE TITLE
can not run this project

### ISSUE THREAD

**Issue by sylviatanggit** [aframevr/aframe-inspector#584]
when i use npm install

the terminal shows this

'NODE_ENV=production cross-env webpack --progress --colors

fatal: not a git repository (or any of the parent directories): .git
child_process.js:669
    throw err;
    ^

Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.<anonymous> (/Users/kanshan/Downloads/aframe-inspector-master/webpack.config.js:29:31)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)'
please  tell me how to solve this problem...

**Comment by vincentfretin** [comment]
Latest master is working for me. @dmarcos you can close.

**Comment by dmarcos** [comment]
No longer an issue. Thanks for reporting
