### ISSUE TITLE
Selecting an entity and pressing escape to unselect gives an error

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#684]
Selecting an entity and pressing escape to unselect is working but gives the following error
```
index.js:165 Uncaught TypeError: Cannot read properties of null (reading 'object3D')
    at Inspector.selectEntity (index.js:165:12)
    at Object.onKeyUp (shortcuts.js:42:24)
```

**Comment by vincentfretin** [comment]
When using Escape, this is called
https://github.com/aframevr/aframe-inspector/blob/aecc85bcd2dde219fc272240bf8bfcd3ebf87b03/src/lib/shortcuts.js#L42
so param entity=null but there is no check for entity null here 
https://github.com/aframevr/aframe-inspector/blob/aecc85bcd2dde219fc272240bf8bfcd3ebf87b03/src/index.js#L165
