### ISSUE TITLE
Using mapped properties in primitive give an error when selecting the entity

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#694]
Modify the index.html example to add `fog="true"` like this:
```html
<a-box id="box" position="0 2 0" height="2" color="#FFC65D" fog="true"></a-box>
```

When you click on the yellow box, the panels disappear and you get the following errors:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'color' in true
    at PropertyRow.render (PropertyRow.js:141:21)
    at finishClassComponent (react-dom.development.js:19752:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
PropertyRow.js:141 Uncaught TypeError: Cannot use 'in' operator to search for 'density' in true
    at PropertyRow.render (PropertyRow.js:141:21)
    at finishClassComponent (react-dom.development.js:19752:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
...
```

a-box here is a primitive and fog="true" is mapped to material.fog.

This is working:
```html
<a-box id="box" position="0 2 0" height="2" color="#FFC65D" material="fog:true"></a-box>
```

**Comment by vincentfretin** [comment]
You can sponsor [vincentfretin](https://github.com/sponsors/vincentfretin) to expedite this fix. Find other work you can sponsor at https://github.com/c-frame/sponsorship

**Comment by vincentfretin** [comment]
With aframe master and
```html
<a-box id="aBox" position="0 2 0" height="2" color="#FFC65D" fog="true"></a-box>
````
it's now an aframe error, not an inspector error:
```
Uncaught (in promise) Error: Component `fog` can only be applied to <a-scene>
    at n.xb (component.js:56:11)
    at new n (component.js:662:15)
    at i.initComponent (a-entity.js:302:17)
    at i.updateComponent (a-entity.js:458:10)
    at i.updateComponents (a-entity.js:429:12)
    at a-entity.js:231:12
    at a-node.js:145:17
```
It seems component name is checked before primitive attributes of an updated schema (material with shader schema src/shaders/standard.js)

Another property like wireframe works without issue (same for color actually):
```html
<a-box id="aBox" position="0 2 0" height="2" color="#FFC65D" wireframe="true"></a-box>
````

I won't investigate this further if the issue is only with property name that conflicts with a component name.
The only conflict we currently have is with fog it seems and we have a workaround of specifying `material="fog:true"`

cc @mrxz in case you think that's a real issue on aframe side that we should fix.

**Comment by mrxz** [comment]
@vincentfretin Attributes for primitives aren't allowed to conflict with component names. Generally this should log a warning when the primitive is instantiated and the attribute gets automatically renamed. The reason this doesn't happen for `fog` (and `visible`) on mesh primitives, is because these conflicts are manually resolved in advance (see [getMeshMixin.js#L15-L16](https://github.com/aframevr/aframe/blob/master/src/extras/primitives/getMeshMixin.js#L15-L16)).

So in the above it was not correct to use `fog="true"` on `<a-box>` to mean `material="fog: true"`; it should've been `material-fog="true"`. The docs have outdated attribute tables that still list `fog` as being mapped to `material.fog`, so that might be the source of the confusion. I have created a PR to update the docs https://github.com/aframevr/aframe/pull/5646

In theory we could allow non scene-only component names to be used for primitive attributes, but I don't think that's worth the effort.
